name: Auto Update Dashboard

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run dashboard
        run: python script_deploy.py
        env:
          GITHUB_ACTIONS: "true"

      - name: Commit updated output
        run: |
          git config --global user.name "dashboard-bot"
          git config --global user.email "bot@github.com"
          git add docs favorites.xlsx || true
          git commit -m "Auto update dashboard" || echo "No changes"
          git push
